"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorCode = void 0;
var ErrorCode;
(function (ErrorCode) {
    ErrorCode["ERROR"] = "ERROR";
    ErrorCode["USER_TOKEN_NOT_FOUND"] = "USER_TOKEN_NOT_FOUND";
    ErrorCode["USER_TOKEN_INVALID"] = "USER_TOKEN_INVALID";
    ErrorCode["PAGE_NOT_FOUND"] = "PAGE_NOT_FOUND";
    ErrorCode["SERVER_ERROR"] = "SERVER_ERROR";
    ErrorCode["UNAUTHORIZED"] = "UNAUTHORIZED";
    ErrorCode["FORBIDDEN"] = "FORBIDDEN";
    ErrorCode["BAD_REQUEST"] = "BAD_REQUEST";
    ErrorCode["TIMEOUT"] = "TIMEOUT";
    ErrorCode["NETWORK_ERROR"] = "NETWORK_ERROR";
    ErrorCode["DATABASE_ERROR"] = "DATABASE_ERROR";
    ErrorCode["FILE_NOT_FOUND"] = "FILE_NOT_FOUND";
    ErrorCode["METHOD_NOT_ALLOWED"] = "METHOD_NOT_ALLOWED";
    ErrorCode["NOT_ACCEPTABLE"] = "NOT_ACCEPTABLE";
    ErrorCode["REQUEST_TIMEOUT"] = "REQUEST_TIMEOUT";
    ErrorCode["TOO_MANY_REQUESTS"] = "TOO_MANY_REQUESTS";
    ErrorCode["INTERNAL_SERVER_ERROR"] = "INTERNAL_SERVER_ERROR";
    ErrorCode["NOT_IMPLEMENTED"] = "NOT_IMPLEMENTED";
    ErrorCode["SERVICE_UNAVAILABLE"] = "SERVICE_UNAVAILABLE";
    ErrorCode["INPUT_INVALID"] = "INPUT_INVALID";
    ErrorCode["INPUT_LENGTH"] = "INPUT_LENGTH";
    ErrorCode["INPUT_NOT_EQUAL"] = "INPUT_NOT_EQUAL";
    ErrorCode["INPUT_REQUIRED"] = "INPUT_REQUIRED";
    ErrorCode["INPUT_TOO_SHORT"] = "INPUT_TOO_SHORT";
    ErrorCode["INPUT_TOO_LONG"] = "INPUT_TOO_LONG";
    ErrorCode["INPUT_OUT_OF_RANGE"] = "INPUT_OUT_OF_RANGE";
    ErrorCode["INPUT_PATTERN_MISMATCH"] = "INPUT_PATTERN_MISMATCH";
    ErrorCode["INPUT_VALUE_TOO_LOW"] = "INPUT_VALUE_TOO_LOW";
    ErrorCode["INPUT_VALUE_TOO_HIGH"] = "INPUT_VALUE_TOO_HIGH";
    ErrorCode["GOOGLE_KEY_NOT_FOUND"] = "GOOGLE_KEY_NOT_FOUND";
    ErrorCode["GOOGLE_KEY_INVALID"] = "GOOGLE_KEY_INVALID";
})(ErrorCode || (exports.ErrorCode = ErrorCode = {}));
//# sourceMappingURL=index.js.map