export default {
    id: "imgDataProps",
    name: "ImgDataProps",
    description: "Interfaz que define las propiedades para configurar la imagen base en el componente Img.",
    props: [
        {
            id: "id",
            type: "string | number (opcional)",
            required: false,
            default: "undefined",
            description: "ID de la imagen.",
        },
        {
            id: "name",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "Nombre de la imagen.",
        },
        {
            id: "alt",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "Texto alternativo de la imagen.",
        },
        {
            id: "src",
            type: "string",
            required: true,
            default: "N/A",
            description: "URL de la imagen.",
        },
        {
            id: "srcMin1920",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "URL de la imagen para pantallas de 1920px o mayores.",
        },
        {
            id: "srcMin1680",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "URL de la imagen para pantallas de 1680px o mayores.",
        },
        {
            id: "srcMin1440",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "URL de la imagen para pantallas de 1440px o mayores.",
        },
        {
            id: "srcMin1024",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "URL de la imagen para pantallas de 1024px o mayores.",
        },
        {
            id: "srcMin992",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "URL de la imagen para pantallas de 992px o mayores.",
        },
        {
            id: "srcMin768",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "URL de la imagen para pantallas de 768px o mayores.",
        },
        {
            id: "srcMin575",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "URL de la imagen para pantallas de 575px o mayores.",
        },
        {
            id: "srcThumbnail_200",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "URL de la imagen en miniatura para tamaños de 200x200px o mayores.",
        },
        {
            id: "srcThumbnail_100",
            type: "string (opcional)",
            required: false,
            default: "undefined",
            description: "URL de la imagen en miniatura para tamaños de 100x100px o mayores.",
        },
    ],
};
